# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_new_class.ui'
#
# Created: Thu Feb  9 22:36:04 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(332, 355)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(332, 355))
        Dialog.setMaximumSize(QtCore.QSize(332, 355))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 158, 25))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bDelete = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.bDelete.setObjectName("bDelete")
        self.horizontalLayout.addWidget(self.bDelete)
        self.bCancel = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.bCancel.setObjectName("bCancel")
        self.horizontalLayout.addWidget(self.bCancel)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 311, 301))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 271, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.prescurtarea = QtGui.QLabel(self.gridLayoutWidget)
        self.prescurtarea.setMargin(10)
        self.prescurtarea.setObjectName("prescurtarea")
        self.gridLayout.addWidget(self.prescurtarea, 3, 0, 1, 1)
        self.fullname = QtGui.QLabel(self.gridLayoutWidget)
        self.fullname.setMargin(10)
        self.fullname.setObjectName("fullname")
        self.gridLayout.addWidget(self.fullname, 2, 0, 1, 1)
        self.prescurtarea_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.prescurtarea_2.setObjectName("prescurtarea_2")
        self.gridLayout.addWidget(self.prescurtarea_2, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 1, 1, 1)
        self.userLevel = QtGui.QComboBox(self.gridLayoutWidget)
        self.userLevel.setObjectName("userLevel")
        self.gridLayout.addWidget(self.userLevel, 2, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.userNameLine = QtGui.QLineEdit(self.gridLayoutWidget)
        self.userNameLine.setObjectName("userNameLine")
        self.gridLayout.addWidget(self.userNameLine, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.uuid = QtGui.QLineEdit(self.gridLayoutWidget)
        self.uuid.setReadOnly(False)
        self.uuid.setPlaceholderText("")
        self.uuid.setObjectName("uuid")
        self.gridLayout.addWidget(self.uuid, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Useer editor", None, QtGui.QApplication.UnicodeUTF8))
        self.bDelete.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.bCancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "User data", None, QtGui.QApplication.UnicodeUTF8))
        self.prescurtarea.setText(QtGui.QApplication.translate("Dialog", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.fullname.setText(QtGui.QApplication.translate("Dialog", "Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "Active", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "UUID", None, QtGui.QApplication.UnicodeUTF8))

